import pool from '../config/sqlPool';

async function createLibraryDatabase() {
  console.log('create database State!!!');
  await pool.query('drop table IF EXISTS bookObject');
  await pool.query('create table bookObject ( id int auto_increment, bookName varchar(250), author longtext, content longtext,isbn varchar(250),images varchar(250),authorId varchar(250), primary key (id))');
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' The World Of Abstract Art', 'Henry Abbey' , '9780500202371'  , 'book1.png ' ,'8' ,'Taschen is a very reliable publishing company when it comes to art books. They are great sources for general information about a topic and can be found at most museums and galleries where English is the primary or secondary language')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' The Best Laid Plans', 'Shidney' , '9781473616851'  , 'book2.jpg ' ,'9' ,'The phrase the best-laid plans is a translation of a Scottish proverb that was first published in 1786. A proverb is a short, pithy, common saying or phrase that particularly gives advice or shares a universal truth. A proverb is an aphorism. Many English proverbs are wise sayings or truths that are taken as quotations from Hebrew biblical scripture, including the Book of Psalms and the Book of Proverbs in the Old Testament, and the Gospel in the New Testament. Other proverbs, or inspirational or wisdom teachings, are taken from the other great religious books, or from a parable told by Aesop, as well as other literature. For instance, the proverb birds of a feather flock together is taken from literature; the phrase early to bed, early to rise, makes a man healthy, wealthy and wise is taken from an almanac. We will examine the meaning of the phrase best-laid plans, where it came from and some examples of its use in sentences.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' The Darkest Night Of Shed', 'Edwin A. Abbott' , '9781473616851'  , 'book3.jpg ' ,'10' ,'The Dark Night of the Shed is a book about Men, the midlife crisis, spirituality and sheds. There comes a point in life when men realise that things have changed. They have spent years climbing the corporate ladder only to find it was leaning against the wrong wall. The odds of being chosen as the next James Bond have diminished to zero.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Eleanor Hallowell Abbott', 'Front Page Fatility' , '0'  , 'book4.jpg ' ,'10' ,'A suspicious accident. A determined reporter. And a ruthless criminal who will stop at nothing to tie up loose ends.  This suspenseful thriller series is recommended for fans of James Patterson, J.D. Robb, and Melinda Leigh.   "...five stars out of five." (Hot Mystery Reviews) When two rookie cops are killed in a fiery crash near Richmond, Virginia, crime reporter Nichelle Clarke is sent in to investigate.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' George Frederick Abbott ', 'Halen Lew Daughter Of Blood' , 'null'  , 'book5.JPG ' ,'11' ,'Malian of Night and Kalan, her trusted ally, are returning to the Wall of Night—but already it may be too late. The Wall is dangerously weakened, the Nine Houses of the Derai fractured by rivalry and hate. And now, the Darkswarm is rising')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values('The Book Store', 'Jacob Abbott ' , '9780500202371'  , 'book6.jpeg ' ,'12' ,' Ajay Mago, owner of the Delhi-based Om Book Shop chain, is angry. “Books are our bread and butter,” the MBA from University of California, Los Angeles, fumes, “but these people are destroying the industry.” The outburst comes when I bring up Flipkart and Amazon, which started as booksellers before burgeoning into all-purpose e-marketplaces. “They don’t want healthy competition and are not bothered about profit,” Mago says. “Books are only crowd-pullers for them. That’s why they throw crazy discounts [up to 45%] that we can never match                                    ')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Assembly Language ', '  Hennie Aucamp ' , '9780500202371'  , 'book7.jpg ' ,'13' ,'An assembly language is a low-level programming language for microprocessors and other programmable devices. It is not just a single language, but rather a group of languages. An assembly language implements a symbolic representation of the machine code needed to program a given CPU architecture.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values('  The Act Of War', 'St. Augustine of Hippo' , '9780500202371'  , 'book9.jpg ' ,'14' ,'An act of war is an action by one country against another with an intention to provoke a war or an action that occurs during a declared war or armed conflict between military forces of any origin. The loss or damage caused due to such conflicts are excluded from insurance coverage except for life assurances.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Flyover People ', 'Jean Auel ' , '9780500202371'  , 'book1.png ' ,'15' ,'Flyover country and flyover states are American phrases describing the parts of the United States between the East and the West Coasts. The terms, which are sometimes used pejoratively, but sometimes used defensively,[1] refer to the interior regions of the country passed over during transcontinental flights ')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Love Story', 'Steve Augarde' , '9780500202371'  , 'book10.jpg ' ,'16' ,' Love Story is a 1970 romance novel by American writer Erich Segal. The book s origins lay in a screenplay that Segal wrote, and that was subsequently approved for production by Paramount Pictures. Paramount requested that Segal adapt the story into novel form as a preview of sorts for the film. The novel was released on February 14, 1970, Valentine s Day. Portions of the story originally appeared in')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' The Massy Grace', 'Jane Austen' , '9780500202371'  , 'book11.jpeg ' ,'17' ,'Carl Massy is a Happiness Strategist who has combined 20 years of international strategic planning with over a decade of training, research and experience in the personal development and Neuro Linguistics Programming (NLP) fields. His two burning question have always been, What can we do, or stop doing to, increase our happiness? and What happiness strategies have the highest happiness return on investment')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values('Once ', 'Paul Auster' , '9780500202371'  , 'book12.jpg ' ,'18' ,'Once is a 2007 Irish romantic musical drama film written and directed by John Carney. The film stars Glen Hansard and Markéta Irglová as two struggling musicians in Dublin, Ireland. Hansard and Irglová had previously performed music as the Swell Season, and composed and performed the films original songs.  ')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' John Hart The HusK', 'Jean Auel' , '9781250012302'  , 'book13.jpg ' ,'15' ,'Hurt came to prominence for his role as Richard Rich in the film A Man for All Seasons (1966) and gained BAFTA Award nominations for his portrayals of Timothy Evans in 10 Rillington Place (1971) and Quentin Crisp in television film The Naked Civil Servant (1975) – winning his first BAFTA for the latter')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Dont Trust Me ', 'Jacob Abbott' , '9780500202371'  , 'book14.jpg ' ,'12' ,' In Can t Hurt Me, he shares his astonishing life story and reveals that most of us tap into only 40% of our capabilities. Goggins calls this The 40% Rule, and his story illuminates a path that anyone can follow to push past pain ')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' To Have & To Hold', 'Henry Abbey' , '9780500202371'  , 'book15.jpg ' ,'8' ,'To Have and to Hold is the story of an English soldier, Ralph Percy, turned Virginian explorer in colonial Jamestown. Ralph buys a wife for himself  a girl named Jocelyn Leigh  little knowing that she is the escaping ward of King James I, fleeing a forced marriage to Lord Carnal. Jocelyn hardly loves Ralph  indeed, she seems to abhor him. Carnal, Jocelyn s husband to be, eventually comes to Jamestown, unaware that Ralph Percy and Jocelyn Leigh are man and wife')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Stephan King', 'Hennie Aucamp' , '9780500202371'  , 'book16.jpg ' ,'13' ,'The Outsiders is a coming-of-age novel by S. E. Hinton, first published in 1967 by Viking Press. Hinton was 15 when she started writing the novel but did most of the work when she was 16 and a junior in high school. Hinton was 18 when the book was published. The book details the conflict between two rival gangs divided by their socioeconomic status the working class "greasers" and the upper class "Socs"  short for Socials). The story is told in first-person perspective by teenaged protagonist Ponyboy Curtis.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Sprak', 'Paul Auster' , '9780500202371'  , 'book17.jpg ' ,'18' ,'Spark is describes a dystopian world set a few years in the future. Because of a world-wide terrorist attack called "The Day of Rage," mass surveillance has become public and pervasive. Almost everyone carries an identification card or a radio-frequency identification chip implanted under the skin. The chip can be read by the Eye system, "allowing the government to track physical movement and determine if an individual is operating outside of his/her normal parameters.')`);
  await pool.query(`insert into bookObject (bookName, author, isbn, images,authorId, content) values(' Sprak', 'Steve Augarde ' , '9780500202371'  , 'book18.jpg ' ,'16' ,' The frame story of Dragon s Time is set during ten days of year 508 AL (years After Landing on Pern). Now it is summer, about six months after the start of the "Third Pass" of the Red Star and its attendant Threadfall. Much of the action takes place during a long episode of time travel led by Fiona of Fort Weyr, who is the Telgar Weyrwoman now (508 AL). The primary purpose of the expedition is to survive, and to mature or to convalesce, and thus to gain man- and dragonpower in the present crisis. ')`);
 
  await pool.query('drop table IF EXISTS authorObject');
  await pool.query('create table authorObject ( authorId int auto_increment, title varchar(250), authorImage varchar(250), content longtext, primary key (authorId))');
  await pool.query(`insert into authorObject(authorImage,title,content) values('author.jpg', 'Haruki Murakami Norwegian Wood','Haruki Murakami, Norwegian Wood is the New York Times bestselling author of Sin in the Second City: Madams, Ministers, Playboys, and the Battle for America s Soul, American Rose: A Nation Laid Bare: The Life and Times of Gypsy Rose Lee, and, most recently, Liar, Temptress, Soldier, Spy: Four Women Undercover in the Civil War, named one  of the best books of 2014 by Library Journal, the Christian Science Monitor, and Amazon. She has written for newyorker.com, the Wall Street Journal, the Washington Post, Smithsonian Magazine, Salon and other publications. Her next book, The Ghosts of Eden Park: The Bootleg King, the Women Who Pursued Him, and the Murder That Shocked Jazz- Age America, will be published by Crown on August 6, 2019')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author3.jpg', 'Karen Abbott','Karen Abbott is the New York Times bestselling author of Sin in the Second City,   American Rose, and, most recently, Liar, Temptress, Soldier, Spy. She has written for the New York  Times Book Review, Wall Street Journal, Smithsonian magazine, Salon, and other publications                                            ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author10.jpg', 'Feisal Abdul Rauf','Feisal Abdul Rauf is the imam of Masjid al-Farah in New York City. Shortly after the attacks of September 11, he appeared on numerous radio and television shows, including BBC World,  ABC News, CBS Evening News, CNN, and 60 Minutes. Born in Kuwait to a long line of imams, Abdul Rauf  was educated in England  ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author4.jpg', ' Michele A’Court','Michele A’Court was born in 1961 and is New Zealand’s best known female comedian (a  term she dislikes, as it makes her sound like a female who happens to be a comedian, rather than just a comedian), with a high profile via regular TV appearances (7 Days, a high-rating current-affairs comedy panel show  ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author6.jpg', ' Elise K. Ackers ','Elise K. Ackers is a freelance editor and award winning fiction author of contemporary romance, romantic suspense, and new adult fiction.                      ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author9.jpg', 'Jim Acosta','Jim Acosta is CNN s chief White House correspondent, currently covering the Trump administration. He previously reported on the Obama administration from the White House and around the  world. He regularly covers presidential press conferences')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author11.jpg', ' S. Daniel Abraham',' S. Daniel Abraham, a leading American entrepreneur and pioneer in both the pharmaceutical and diet food business, is the creator of Slim-Fast Foods, the most successful diet product in history. A well-known philanthropist, his gift to the Mayo Clinic served to create the Da  Abraham Healthy Living Center.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('henry.jpg', 'Henry Abbey',' Abbey was born in Rondout (now a part of Kingston), New York, the son of Stephen Abbey, a merchant of farm products, and Caroline Vail. His family was moderately successful and able to support his attendance at Kingston Academy, the Delaware Literary Institute in Delhi, New York, and the Hudson River Institute across the river in Columbia County, but the uncertain grain and feed business was insufficient to enable him to attend college.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('sidney.jpg', 'Shidney','Sheldon was born Sidney Schechtel in Chicago, Illinois. His parents, of Russian Jewish ancestry, were Ascher "Otto" Schechtel (1894–1967), manager of a jewelry store, and Natalie Marcus. At 10, Sidney made his first sale, US$5 for a poem. During the Depression, he worked at a variety of jobs, and after graduating from East High School, he attended Northwestern University on a scholarship and contributed short plays to drama groups. He had to drop out after six months during the Depression era to help support his family.[6] Sheldon enlisted in the military during World War II. ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('edwin.jpg', 'Edwin Abbott',' Edwin Abbott Abbott, English schoolmaster and theologian, is best known as the author of the mathematical satire Flatland (1884). He was educated at the City of London School and at St John s College, Cambridge, where he took the highest honours in classics, mathematics and theology, and became fellow of his college. In 1862 he took orders. After holding masterships at King Edward s School, Birmingham, and at Clifton College, he succeeded G. F. Mortimer as headmaster of the City of London School in 1865 at the early age of twenty-six. He was Hulsean lecturer in 1876.         ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('george.jpg', ' George Frederick abbort','Abbott was born in Forestville, New York, to George Burwell Abbott (May 1858 Erie County, New York – February 4, 1942 Hamburg, New York) and Hannah May McLaury (1869 – June 20, 1940 Hamburg, New York). He later moved to the town of Salamanca, which twice elected his father mayor. In 1898, his family moved to Cheyenne, Wyoming, where he attended Kearney Military Academy. Within a few years, his family returned to New York, and he graduated from Hamburg High School in 1907. Four years later, he obtained a Bachelor of Arts degree from the University of Rochester,[1] where he wrote his first play, Perfectly Harmless, for the University Dramatic Club.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('jacob.jpeg', 'jacob abbott','Abbott was born at Hallowell, Maine to Jacob and Betsey Abbott. He graduated from Bowdoin College in 1820; studied at Andover Theological Seminary in 1821, 1822, and 1824; was tutor in 1824-1825, and from 1825 to 1829 was professor of mathematics and natural philosophy at Amherst College; was licensed to preach by the Hampshire Association in 1826; founded the Mount Vernon School for Young Ladies in Boston in 1829, and was principal of it in 1829-1833; was pastor of Eliot Congregational Church (which he founded), at Roxbury, Massachusetts in 1834-1835; and was, with his brothers, a founder, and in 1843-1851 a principal of Abbott s Institute, and in 1845-1848 of the Mount Vernon School for Boys, in New York City.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('hennie.jpeg', 'Hennier Aucamp','Hennier Aucamp Hendrik Christoffel Lourens (Hennie) Aucamp (1934-2014) was a South African writer and poet who gained prominence as an academic, playwright, short story and cabaret writer. ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('st.jpg', 'st. Augestin of hippo','Saint Augustine of Hippo  was a Roman African, early Christian theologian and philosopher from Numidia whose writings influenced the development of Western Christianity and Western philosophy. He was the bishop of Hippo Regius in North Africa and is viewed as one of the most important   ')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('jean.jpg', 'Jean M. Auel','Jean M. Auel, née Jean Marie Untinen is an American author best known for her Earth s Children books, a series of historical fiction novels set in prehistoric Europe that explores interactions of Cro-Magnon people with Neanderthals. As of 2010 her books have sold more than 45 million copies worldwide, in many translations. Auel attended University of Portland, and earned an MBA in 1976. She received honorary degrees from her alma mater, as well as the University of Maine and the Mount Vernon College for Women. She and her husband, Ray Bernard Auel, have five children and live in Portland, Oregon.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('author11.jpg', 'Steve Augarde',' Steve Augarde (born 3 Oct 1950) is a British author and artist. He has written and illustrated several novels for children and young adults as well as over seventy picture books for younger children, including pop-up books for which he designed the paper engineering.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('jane.jpeg', ' jane Austen ','Jane Austen 16 December 1775 – 18 July 1817) was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century. Austen s plots often explore the dependence of women on marriage in the pursuit of favourable social standing and economic security.')`);
  await pool.query(`insert into authorObject(authorImage,title,content) values('auster.jpeg', 'Paul Auster','Paul Benjamin Auster (born February 3, 1947) is an American writer and film director. His notable works include The New York Trilogy (1987), Moon Palace (1989), The Music of Chance (1990), The Book of Illusions (2002), The Brooklyn Follies (2005), Invisible (2009), Sunset Park (2010), Winter Journal (2012), and 4 3 2 1 (2017). His books have been translated into more than forty languages.')`);
  console.log('completed!!');
}
createLibraryDatabase();
